sonar.projectKey=NoTIPswe_notip-frontend
sonar.organization=notipswe

sonar.sources=src
sonar.exclusions=**/*.spec.ts, src/environments/**, src/app/generated/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.coverage.exclusions=\
	src/app/app.config.ts,\
	src/app/app.routes.ts,\
	src/app/core/auth/contracts.ts,\
	src/app/core/models/**/*.ts,\
	src/main.ts,\
	src/test-setup.ts,\
	src/app/**/pages/**/*.page.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-reporter.xml
sonar.eslint.reportPaths=eslint-report.json
sonar.typescript.tsconfigPath=tsconfig.json